locals {
  cluster_color             = "orange"
  cluster_role_color        = "red"
  configmap_color           = "green"
  ingress_color             = "red"
  node_color                = "orange"
  container_color           = "orange"
  role_color                = "red"
  definition_color          = "blue"
  service_color             = "deeppink"
  namespace_color           = "green"
  endpoint_color            = "purple"
  persistent_volume_color   = "green"
  pod_security_policy_color = "red"
}
