locals {
  kubernetes_deployment_icon        = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/deployment.svg"))
  kubernetes_pod_icon               = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/pod.svg"))
  kubernetes_replicaset_icon        = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/replicaset.svg"))
  kubernetes_namespace_icon         = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/namespace.svg"))
  kubernetes_service_icon           = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/service.svg"))
  kubernetes_node_icon              = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/node.svg"))
  kubernetes_daemonset_icon         = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/daemonset.svg"))
  kubernetes_statefulset_icon       = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/statefulset.svg"))
  kubernetes_job_icon               = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/job.svg"))
  kubernetes_cronjob_icon           = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/cronjob.svg"))
  kubernetes_configmap_icon         = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/configmap.svg"))
  kubernetes_crd_icon               = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/crd.svg"))
  kubernetes_endpoint_icon          = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/endpoint.svg"))
  kubernetes_ingress_icon           = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/ingress.svg"))
  kubernetes_networkpolicy_icon     = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/networkpolicy.svg"))
  kubernetes_role_icon              = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/role.svg"))
  kubernetes_secret_icon            = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/secret.svg"))
  kubernetes_cluster_icon           = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/cluster.svg"))
  kubernetes_psp_icon               = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/psp.svg"))
  kubernetes_persistent_volume_icon = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/persistentvolume.svg"))
  kubernetes_rolebinding_icon       = format("%s,%s", "data:image/svg+xml;base64", filebase64("./icons/rolebinding.svg"))
}
